import jsPDF from "jspdf";

export const handleDownloadPdf = () => {
  const data = getValues(); // grab whatever is currently typed

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const left = 48;
  let y = 64;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Preqly™ — Pre-Approval Application", left, y);
  y += 24;
  doc.setDrawColor(230);
  doc.line(left, y, 547, y);
  y += 24;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const rows = [
    ["Full Name", data.fullName],
    ["Email", data.email],
    ["Phone Number", data.phoneNumber],
    ["Property Zip Code", data.propertyZipCode],
    ["Property Address", data.propertyAddress],
    ["Annual Income", data.annualIncome],
    ["Purchase Price", data.purchasePrice],
    ["Down Payment", data.downPayment],
    ["Loan Purpose", data.loanPurpose],
    ["Cash Out Amount", data.cashOutAmount],
  ];

  rows.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, left, y);
    doc.setFont("helvetica", "normal");
    doc.text(String(value || "—"), left + 160, y, { maxWidth: 360 });
    y += 18;
    if (y > 760) {
      doc.addPage();
      y = 64;
    }
  });

  y += 16;
  doc.setDrawColor(230);
  doc.line(left, y, 547, y);
  y += 20;
  doc.setFontSize(9);
  doc.text("Generated by Preqly — for review purposes only.", left, y);

  doc.save("Preqly-PreApproval.pdf");
};
